mavros_node:
  ros__parameters:
    # Target 14551 is standard for external developer APIs in SITL
    fcu_url: "udp://127.0.0.1:14551@14555"
    gcs_url: ""
    target_system_id: 1
    fcu_connection_timeout: 5.0
    use_sim_time: true