# Clock
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# Joint states
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/map/model/iris/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# Odometry, if you use it
- ros_topic_name: "/odometry"
  gz_topic_name: "/model/iris/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# RGB camera
- ros_topic_name: "/camera/image"
  gz_topic_name: "/world/map/model/iris/link/depth_camera_link/sensor/rgb_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/world/map/model/iris/link/depth_camera_link/sensor/rgb_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# Depth
- ros_topic_name: "/camera/depth"
  gz_topic_name: "/world/map/model/iris/link/depth_camera_link/sensor/depth_camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# Lidar (only if you keep it)
- ros_topic_name: "/scan"
  gz_topic_name: "/world/map/model/iris/link/base_scan/sensor/gpu_lidar/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# IMU
- ros_topic_name: "/imu"
  gz_topic_name: "/world/map/model/iris/link/imu_link/sensor/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# Battery
- ros_topic_name: "/battery"
  gz_topic_name: "/model/iris/battery/linear_battery/state"
  ros_type_name: "sensor_msgs/msg/BatteryState"
  gz_type_name: "gz.msgs.BatteryState"
  direction: GZ_TO_ROS
